#!/usr/bin/env node

/**
 * Flattens the @import tree of index.css into a single file.
 *
 * Served raw over a <link>, the entry point costs three sequential round trips:
 * the browser cannot discover tokens/index.css until index.css has arrived and
 * been parsed, nor colors.css until that one has. Bundlers resolve this at
 * build time; consumers loading the CSS directly do not.
 *
 * Inlining is safe here because every file declares its own @layer (ADR-004),
 * so concatenating them just merges layers of the same name, and the canonical
 * order still comes from the @layer statement at the top of index.css.
 *
 * Runs on prepack, so the output ships in the tarball without being committed.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(ROOT, "index.css");
const OUT = join(ROOT, "dist", "artphil-design-system.css");

const IMPORT = /^[ \t]*@import\s+"([^"]+)"\s*;[ \t]*$/gm;

function inline(file, seen = new Set()) {
  const path = resolvePath(file);
  if (seen.has(path)) {
    throw new Error(`import cycle at ${path.slice(ROOT.length + 1)}`);
  }
  seen.add(path);

  return readFileSync(path, "utf8").replace(IMPORT, (_, target) =>
    inline(join(dirname(path), target), new Set(seen)).trim(),
  );
}

const banner = `/* artphil-design-system — generated by scripts/build-css.mjs, do not edit */\n\n`;
const css =
  banner +
  inline(ENTRY)
    .replace(/\n{3,}/g, "\n\n")
    .trim() +
  "\n";

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css);

const kb = (n) => `${(n / 1024).toFixed(1)} kB`;
console.log(
  `\n  dist/artphil-design-system.css — ${kb(Buffer.byteLength(css))}, ` +
    `${css.split("\n").length} linhas, 0 @import restantes\n`,
);
